FLAG	= -std=c++14 -g -03 -Wall

main01.o: main01.C
	g++ -c -o main01.o main01.C

main02.o: main02.C
	g++ -c -o main02.o main02.C

try01: main01.o
	g++ -o try01 main01.o

try02: main02.o
	g++ -o try02 main02.o


